---
service_account_id: "{{ vault_service_account_id }}"
key_id: "{{ vault_key_id }}"

instance_ip: "{{ vault_instance_ip }}"
instance_name: "{{ vault_instance_name }}"

private_key: "{{ vault_private_key }}"

nginx_remove_default_vhost: true

nginx_domain: 'evarun.ru'
nginx_port: '80'
nginx_proxy_pass:  |
  location / {
    add_header Access-Control-Allow-Origin *;

    proxy_set_header Host {{ item.name }}.{{nginx_domain}};
    proxy_pass http://{{ item.name }};
  }

nginx_services:
  - { name: 'gateway', port: '7000'}
  - { name: 'auth', port: '7002'}
  - { name: 'position', port: '7003'}
  - { name: 'billing', port: '7004'}
  - { name: 'push', port: '7005'}
  - { name: 'pma', port: '7050'}

users:
  - name: aeremin
    sudo: true
    sudo_nopasswd: true
    ssh_key: "{{vault_aeremin_key}}"
