---
service_account_id: "{{ vault_service_account_id }}"
key_id: "{{ vault_key_id }}"

instance_ip: instance.evarun.ru
instance_name: "{{ vault_instance_name }}"

private_key: "{{ vault_private_key }}"

nginx_remove_default_vhost: true

nginx_domain: 'evarun.ru'
nginx_port: '80'
nginx_port_ssl: '443 ssl'
nginx_proxy_pass:  |
  location / {
    {{ item.headers }}

    proxy_set_header Host {{ item.name }}.{{nginx_domain}};
    proxy_pass http://{{ item.name }};
  }

nginx_ssl_cert:  |
  ssl_certificate     /etc/letsencrypt/live/{{ item.name }}.{{nginx_domain}}/fullchain.pem;
  ssl_certificate_key /etc/letsencrypt/live/{{ item.name }}.{{nginx_domain}}/privkey.pem;
  ssl_protocols       TLSv1 TLSv1.1 TLSv1.2;
  ssl_ciphers         HIGH:!aNULL:!MD5;

ngixn_add_header_cors: |
  if ($request_method = 'OPTIONS') {
      add_header 'Access-Control-Allow-Origin' '*';
      add_header 'Access-Control-Allow-Methods' '*';
      add_header 'Access-Control-Allow-Headers' '*';

      add_header 'Access-Control-Max-Age' 1728000;
      add_header 'Content-Type' 'text/plain; charset=utf-8';
      add_header 'Content-Length' 0;
      return 204;
  }

  add_header 'Access-Control-Allow-Origin' '*' always;
  add_header 'Access-Control-Allow-Methods' '*' always ;
  add_header 'Access-Control-Allow-Headers' '*' always;
  add_header 'Access-Control-Expose-Headers' 'Content-Length,Content-Range' always;

nginx_services:
  - { name: 'gateway', port: '7000', headers: "{{ ngixn_add_header_cors }}", ssl: false}
  - { name: 'auth', port: '7002', headers: "{{ ngixn_add_header_cors }}", ssl: false}
  - { name: 'position', port: '7003', headers: "{{ ngixn_add_header_cors }}", ssl: true}
  - { name: 'push', port: '7005', headers: '', ssl: false}
  - { name: 'model-engine', port: '7006', headers: '', ssl: false}
  - { name: 'models-manager', port: '7007', headers: '', ssl: false}
  - { name: 'billing', port: '7009', headers: '', ssl: false}
  - { name: 'web', port: '7011', headers: '', ssl: true}
  - { name: 'web-backend', port: '7010', headers: '', ssl: false}
  - { name: 'admin-client', port: '7013', headers: '', ssl: true}
  - { name: 'ppa', port: '7051', headers: '', ssl: false}
  - { name: 'grafana', port: '7030', headers: '', ssl: false}

users:
  - name: aeremin
    sudo: true
    sudo_nopasswd: true
    ssh_key: "{{vault_aeremin_key}}"

certbot_create_if_missing: true
certbot_admin_email: tenevoybeg2020@gmail.com
certbot_certs:
 - email: tenevoybeg2020@gmail.com
   domains:
     - auth.evarun.ru
 - email: tenevoybeg2020@gmail.com
   domains:
     - web.evarun.ru
 - email: tenevoybeg2020@gmail.com
   domains:
     - admin-client.evarun.ru
 - email: tenevoybeg2020@gmail.com
   domains:
     - position.evarun.ru

certbot_auto_renew: false
