---
service_account_id: "{{ vault_service_account_id }}"
key_id: "{{ vault_key_id }}"

instance_ip: "{{ vault_instance_ip }}"
instance_name: "{{ vault_instance_name }}"

private_key: "{{ vault_private_key }}"

nginx_remove_default_vhost: true

nginx_domain: 'evarun.ru'
nginx_port: '80'
nginx_proxy_pass:  |
  location / {
    {{ item.headers }}

    proxy_set_header Host {{ item.name }}.{{nginx_domain}};
    proxy_pass http://{{ item.name }};
  }

ngixn_add_header_cors: 'add_header Access-Control-Allow-Origin *;'

nginx_services:
  - { name: 'gateway', port: '7000', headers: "{{ ngixn_add_header_cors }}"}
  - { name: 'auth', port: '7002', headers: "{{ ngixn_add_header_cors }}"}
  - { name: 'position', port: '7003', headers: "{{ ngixn_add_header_cors }}"}
  - { name: 'push', port: '7005', headers: ''}
  - { name: 'model-engine', port: '7006', headers: ''}
  - { name: 'models-manager', port: '7007', headers: ''}
  - { name: 'pma', port: '7050', headers: ''}
  - { name: 'ppa', port: '7051', headers: ''}

users:
  - name: aeremin
    sudo: true
    sudo_nopasswd: true
    ssh_key: "{{vault_aeremin_key}}"
