---
dependency:
  name: galaxy
  requirements_file: requirements.yml

driver:
  name: docker

lint:
  name: yamllint

platforms:
  - name: ubuntu-bionic
    image: ubuntu:bionic

provisioner:
  name: ansible
  options:
    diff: true
    v: true
  log: true
  lint:
    name: ansible-lint

scenario:
  name: default

verifier:
  name: testinfra
  options:
    disable-pytest-warnings: true
    v: true
  lint:
    name: flake8
